sh_binary(
    name = "foo",
    srcs = ["foo.sh"]
)

sh_binary(
    name = "foo1",
    srcs = ["foo1.sh"]
)

sh_binary(
    name = "foo2",
    srcs = ["foo2.sh"]
)

sh_binary(
    name = "foo3",
    srcs = ["foo3.sh"]
)
